<?php

namespace AppBundle\Repository;

/**
 * ActeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeurRepository extends \Doctrine\ORM\EntityRepository
{
    //SEVEN Sélectionner le **nom des acteurs français** ayant joué dans des films de **Steven Spielberg**
    public function querySeven()
    {
        $results = $this
            ->createQueryBuilder('as_acteur')
            ->select('as_acteur.nom AS n')
            ->join('as_acteur.pays', 'pays')
            ->join('as_acteur.films', 'film')
            ->join('film.realisateurs', 'realisateur')
            ->where('pays.nom LIKE :param1')
            ->andWhere('realisateur.prenom LIKE :param2')
            ->andWhere('realisateur.nom LIKE :param3')

            ->setParameters([
                'param1' => '%France%',
                'param2' => '%steven%',
                'param3' => '%spielberg%',
            ])
            ->getQuery()
            ->getResult();

        return $results;
    }

    //NINE Sélectionner le **nom des acteurs** et les classer par **ordre alphabétique**
    public function queryNine()
    {
        $results = $this
            ->createQueryBuilder('as_acteur')
            ->select('as_acteur.nom AS nom')
            ->orderBy('nom', 'ASC')
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

}
