<?php

namespace AppBundle\Repository;

/**
 * RealisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisateurRepository extends \Doctrine\ORM\EntityRepository
{

    public function queryTwo()
    {
        $results = $this
            //on crée la requête et on définit l'alias
            ->createQueryBuilder('real')
            //on select en utilisant l'alias
            ->select('real.nom AS realnom')
            ->getQuery()
            ->getResult();

        return $results;
    }

    //TEN Sélectionner le **nombre de films par réalisateur** et les classer par **ordre alphabétique**
    public function queryTen()
    {
        $results = $this
            ->createQueryBuilder('as_real')
            ->select('as_real.nom AS n, COUNT(film.id) AS c')
            ->join('as_real.films','film')
            ->groupBy('n')
            ->orderBy('n', 'ASC')
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }
}
